/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author munnaraju
 */
public class HomePanel extends javax.swing.JPanel implements MouseListener {

    JLabel label[] = new JLabel[20];
    static int i;
    static String self;
    String[] user;
    static int globalvar = 0;
    BorderLayout borderLayout;
    JMenuBar menuBar;
    JMenu fileMenu;
    JMenuItem sendPhotoItem;
    ChatPanel cp;
    String un;
    static int self_id;

    /**
     * Creates new form HomePanel
     */
    public HomePanel(String username) {
        initComponents();
        displayHomeMenu();
        un = username;

        userNamePanel.setLayout(new GridLayout(10, 1));
        timer.start();
    }
    Timer timer = new Timer(5000, new ActionListener() {

        public void actionPerformed(ActionEvent e) {

            userNamePanel.removeAll();
            userNamePanel.updateUI();

            System.out.println(InputParser.userList);

//            if(IP.userList.contains("GID"))
//                JOptionPane.showMessageDialog(menuHomePanel, "COntains GID");
//
//            if (IP.userList.contains("Joined") || IP.userList.contains("quit")) {
//                System.out.println("Message contain joined or quit");
//            } else {

            for (i = 0; i < IP.users.length; i++) {

                final String uname = IP.users[i];



                if (uname != null) {


                    int a = uname.indexOf("#");
                    String current_user = uname.substring(2, a);
                    if (un.equalsIgnoreCase(current_user)) {
                        System.out.println("Current user:" + current_user + " User:" + un);
                    } else {

                        label[i] = new JLabel(i + 1 + "." + uname);
                        label[i].setSize(20, 10);
                        userNamePanel.add(label[i]);

                        label[i].addMouseListener(new MouseListener() {

                            public void mouseClicked(MouseEvent e) {

//                            JOptionPane.showMessageDialog(menuHomePanel, uname);
//                            InputParser ip =new InputParser();
//                            ip.getUserID(uname);
                                System.out.println("Clicked on " + uname);
                                try {
                                    setOne();
                                    int a = uname.indexOf("#");
                                    System.out.println("ID is: " + uname.charAt(a + 1));

                                    MainFrame.out.writeUTF("AG:" + uname.charAt(a + 1));
                                    self = uname;
                                    self_id = Integer.parseInt(String.valueOf(uname.charAt(a + 1)));
                                    System.out.println("SELF ID = " + self_id);
                                    JFrame frame = new JFrame();
                                    frame.setTitle("MC" + uname);
                                    frame.setSize(422, 416);
                                    frame.setVisible(true);
                                    frame.setResizable(false);
                                    //ChatPanel cp = new ChatPanel();
                                    PrivateChat cp = new PrivateChat(uname, self_id);
                                    frame.getContentPane().add(cp);

                                } catch (Exception evt) {
                                    System.out.println("XXXXXXXXXXXXX");
                                }
                            }

                            public void mousePressed(MouseEvent e) {
                            }

                            public void mouseReleased(MouseEvent e) {
                            }

                            public void mouseEntered(MouseEvent e) {
                            }

                            public void mouseExited(MouseEvent e) {
                            }
                        });

                        userNamePanel.revalidate();
                    }
                }
            }
            System.out.println("timer acivated");
            userNamePanel.repaint();
            //}
        }
    });

    public void setOne() {
        globalvar = 1;


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userNamePanel = new javax.swing.JPanel();
        menuHomePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        inputArea = new javax.swing.JTextArea();
        sendButton = new javax.swing.JButton();

        userNamePanel.setLayout(null);

        javax.swing.GroupLayout menuHomePanelLayout = new javax.swing.GroupLayout(menuHomePanel);
        menuHomePanel.setLayout(menuHomePanelLayout);
        menuHomePanelLayout.setHorizontalGroup(
            menuHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 505, Short.MAX_VALUE)
        );
        menuHomePanelLayout.setVerticalGroup(
            menuHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel4.setText("Users Online");

        inputArea.setColumns(20);
        inputArea.setRows(5);
        jScrollPane2.setViewportView(inputArea);

        sendButton.setText("Send");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(sendButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(userNamePanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))))
                    .addComponent(menuHomePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuHomePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(userNamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sendButton, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        // TODO add your handling code here:
        if (inputArea.getText().equals("")) {
        } else {

            try {

                MainFrame.out.writeUTF(inputArea.getText());
                MainFrame.out.flush();
                inputArea.setText("");
            } catch (IOException ex) {
                Logger.getLogger(ChatPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_sendButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea inputArea;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel menuHomePanel;
    private javax.swing.JButton sendButton;
    private javax.swing.JPanel userNamePanel;
    // End of variables declaration//GEN-END:variables
//public boolean userNamePanelLabelMouseEnteredActionPerformed(java.awt.event.ActionEvent evt){
//    if()
//    
//    
//}

    public void mouseClicked(MouseEvent me) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public void mousePressed(MouseEvent me) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public void mouseReleased(MouseEvent me) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public void mouseEntered(MouseEvent me) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public void mouseExited(MouseEvent me) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public void displayHomeMenu() {
        FlowLayout flowLaout = new FlowLayout();
        menuHomePanel.setLayout(flowLaout);
        flowLaout.setVgap(0);
        flowLaout.setAlignment(FlowLayout.LEFT);

        JMenuBar menuBar = new JMenuBar();

        JMenu buddiesMenu = new JMenu("Buddies");
        JMenu toolsMenu = new JMenu("Tools");
        JMenu optionMenu = new JMenu("Option");
        JMenu helpMenu = new JMenu("Help");

        JMenuItem addBuddyMenuItem = new JMenuItem("Add Buddy");
        JMenuItem exitMenuItem = new JMenuItem("Exit");

        JMenuItem preferenceMenuItem = new JMenuItem("Preferences");
        JMenuItem pluginMenuItem = new JMenuItem("Plugin");

        JMenuItem soundEnableMenuItem = new JMenuItem("Enable Sound");
        JMenuItem logginEnableMenuItem = new JMenuItem("Enable Logging");
        JMenuItem enableToolbar = new JMenuItem("Enable Toolbar");

        JMenuItem helpMenuItem = new JMenuItem("Help Contents");
        JMenuItem aboutMenuItem = new JMenuItem("About");
        JMenuItem creditMenuItem = new JMenuItem("Credit");



        menuHomePanel.add(menuBar);

        menuBar.add(buddiesMenu);
        menuBar.add(toolsMenu);
        menuBar.add(optionMenu);
        menuBar.add(helpMenu);

        optionMenu.add(soundEnableMenuItem);
        optionMenu.add(logginEnableMenuItem);
        optionMenu.add(enableToolbar);

        helpMenu.add(helpMenuItem);
        helpMenu.add(aboutMenuItem);
        helpMenu.add(creditMenuItem);

        buddiesMenu.add(addBuddyMenuItem);
        buddiesMenu.add(exitMenuItem);

        toolsMenu.add(preferenceMenuItem);
        toolsMenu.add(pluginMenuItem);

        helpMenuItem.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent ae) {

                JFrame helpContentFrame = new JFrame();
                helpContentFrame.setVisible(true);
                helpContentFrame.setSize(603, 365);
                HelpContents hc = new HelpContents();
                helpContentFrame.getContentPane().add(hc);
            }
        });



        creditMenuItem.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent ae) {
                JTextArea messageTextArea = new JTextArea(10, 25);
                messageTextArea.setOpaque(false);
                messageTextArea.setEditable(false);
                messageTextArea.setText("Surehs Lamgard (@rockrulzz47)" + "\n" + "Diapk Panta (@nimbusXnimbus)" + "\n" + "Raju Gotame (@munnaraju)");
                final ImageIcon icon = new ImageIcon("images/about5.png");
                JOptionPane.showMessageDialog(null, messageTextArea, "About", JOptionPane.INFORMATION_MESSAGE, icon);



            }
        });

        exitMenuItem.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent ae) {
                System.exit(0);
            }
        });
        aboutMenuItem.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent ae) {
                JTextArea messageTextArea = new JTextArea(10, 25);
                messageTextArea.setOpaque(false);
                messageTextArea.setEditable(false);
                messageTextArea.setText("Hello" + "\n" + "How r u ?" + "\n" + "my name is raju" + "\n" + "I live in chitwan");
                ImageIcon icon = new ImageIcon("images/about5.png");
                JOptionPane.showMessageDialog(null, messageTextArea, "About", JOptionPane.INFORMATION_MESSAGE, icon);




            }
        });

    }
}
